project_name: gonauta

dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: gonauta
    main: ./main.go
    binary: gonauta
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitDate }}'

archives:
  - id: default
    builds:
      - gonauta
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    files:
      - LICENSE
      - README.md

nfpms:
  - id: deb
    package_name: gonauta
    file_name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Arch }}'
    homepage: https://github.com/yosle/gonauta
    description: Cliente CLI para gestionar conexiones a Nauta con soporte VPN automático.
    maintainer: GoNauta Team <opensource@yosle.dev>
    license: MIT
    vendor: GoNauta
    formats:
      - deb
    bindir: /usr/local/bin

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

signs:
  - artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
